const SELECIONADO = "#1AAE9E";

const BORDASELECIONADO = "#0E7D71";

const DISPONIVEL = "#C3CFD9";

const BORDADISPONIVEL = "#808F9D";

const INDISPONIVEL = "#FBE192";

const BORDAINDISPONIVEL = "#F7C52B";

export {SELECIONADO, BORDASELECIONADO, DISPONIVEL, BORDADISPONIVEL, INDISPONIVEL, BORDAINDISPONIVEL};